### PR TITLE
Lua implementation

### PR DESCRIPTION
**Pull request by bluebird75**
In addition to Java, I worked on a Lua implementation (very close to python, except for the array indices starting from 1 ). I actually plan to use this implementation in LuaUnit.

### CODE REVIEW

**Comment by bluebird75** [comment]
ping

**Comment by paulgb** [comment]
Thanks Philippe, sorry for the slow merge; I didn't have Lua on my system before.

**Comment by paulgb** [comment]
Are you ok with the Lua and Java versions being zlib/libpng license as well?

**Comment by bluebird75** [comment]
Sure, I am ok with the license.
Maybe making it Java 7 compliant would be a good idea. I don't have time right now for this but I'll consider it sometimes during the year.

**Pull request merged**
