### PR TITLE
Remove a small bit

### PR DESCRIPTION
**Pull request by ionescho**
The line of code should be clearer now.

### CODE REVIEW

**Comment by twk3** [comment]
It's not exactly logically equivalent. As in the case of iold = undefined (which would be what would happen as a result of the default case on line 84) You are now checking the overlap[NaN] for a value. Which of course shouldn't be set, but if we had made a similar mistake when setting the values, it could be.

**Comment by ionescho** [comment]
overlap[NaN] === undefined and (undefined || 0 ) === 0 , therefore this shouldn't cause any issues.

**Comment by twk3** [comment]
overlap[NaN] equals whatever you might have stored in overlap[NaN]
Which in this case won't be anything and will === undefined. But as a result I don't think the line of code is clearer.

**Comment by ionescho** [comment]
Ok, the reason I did this pull request was that, when I was first reading this, I was squinting my eyes hard at this line and a shorter equivalent expression would have eased the comprehension process ( at least for me ). Paulgb is the one who decides in the end if he wants to merge or not right?

**Comment by paulgb** [comment]
I'm going to go with @twk3 on this since it's his code and I haven't done enough JS lately to have an opinion.

**Pull request closed without merging**
