### PR TITLE
Modernise python package installation

### PR DESCRIPTION
**Pull request by djmattyg007**

### CODE REVIEW

**Comment by paulgb** [comment]
Looks good, thank you!

**Comment by djmattyg007** [comment]
Wow, thanks for such a quick review! Do you need assistance publishing a new version to PyPI?

**Comment by paulgb** [comment]
I was able to upload, can you confirm that it worked? https://pypi.org/project/simplediff/1.1/

**Comment by djmattyg007** [comment]
Yep! Thank you so much! :smiley:

**Pull request merged**
